name: Spack Build Cache

on:
  pull_request: []
#  schedule:
#    - cron: "0 * * * *"

jobs:

  # Note: this randomly selects 25 spack packages to build, for the build-binaries step
  # You can update this matrix generation step to derive packages however you like
  prepare:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    outputs:
      packages: ${{ steps.choose.outputs.packages }}

  build-binaries:
    runs-on: ubuntu-latest
    needs:
      - prepare
    permissions:
      packages: write
    strategy:
      fail-fast: false

    name: Build Package Binaries
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build Spack Package
        uses: vsoch/spack-package-action/package@develop
        id: package
        with:
          package: tiramisu
          token: ${{ secrets.GITHUB_TOKEN }}
          deploy: ${{ github.event_name != 'pull_request' }}

      - name: Update Build Cache
        uses: vsoch/spack-package-action/buildcache@develop
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          user: ${{ secrets.DEPLOY_USER }}
          deploy: ${{ github.event_name != 'pull_request' }}
